<?php

namespace App;


use Illuminate\Database\Eloquent\Model;

class Pagamento extends Model {
    protected $table ='pagamentos';
    protected $fillable =[
        'id','valor','forma','numrecibo','dataP'
    ];

    public function save1(array $options = [])
    {
        return parent::save($options); // TODO: Change the autogenerated stub
    }

    public function salvarrr(Pagamento $pagamento){
//        $pagamento = $pagamento->crea;
//        try{
//            $pagamento->save();
//            return 'salvo';
//        }catch (Exception $e){
//            return "Erro ".$e->getMessage();
//        }
    }
}
